# Generated by Django 5.0 on 2024-01-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getLinkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(blank=True, max_length=5000, null=True)),
                ('link_address', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
